# Discussion

Measurements on match advantages and mental rotation scores not only revealed the variations of individuals and items but also showed the differences of laboratories and languages. The two planned analysis plans, meta-analysis and mixed-effect models, lead to the divided results. The meta-analysis of match advantages showed the overall orientation effect across the investigated languages, but the language-specific meta-analysis indicated that only German data showed the significant orientation effect. On the other hand, the mixed-effect model did not indicate either the overall effect or the languag-specific effect.

Contrary to the match advantages, mixed-effect models indicated significant imagery scores for each investigated language. Regarding the planned regression analysis, it is diffucult to the evaluate the predictability of mental rotation scores on the match advantages because of the various results. We summarize the lessons learned on the methodology, analysis, and theoretical issues and attempt to address in which aspect the hypotheses obtained the (dis)confirmative evidence from the current findings.

## Methodology  issues

Our data collection deviated from the preregistered plan because 18 laboratories (one-third of registered laboratories) collected data on the Internet due to the emergence of the Covid-19 pandemic. Because the measurement precision of web-based data is debating [e.g., @anwyl-irvineGorillaOurMidst2020; @bridgesTimingMegastudyComparing2020a; @deleeuwPsychophysicsWebBrowser2016], we eventually filtered the outliers in terms of participants’ response times instead of the laboratory-based criterion. With the lowest exclusion rate (`r round(100*sum(Raw_total$N_excluded)/sum(Raw_total$N),2)`%), the fitted mixed-effect model confirmed no difference of response times between on-site and Internet data. Although we mixed the two data sets in the final data analysis, it is worth considering that Internet participants’ attention may be easily distracted given the lack of any environmental control and lack of experimenter assistance.

When using  sentence-picture verification task as a comprehension task, researchers have had to insert the comprehension questions or memory checks among the experimental trials [@chenDoesObjectSize2020; @stanfield_effect_2001]. @kaschakEmbodimentLabTheory2021 pointed out this setting could trigger the participants to consciously generate mental imagery while reading the probe sentence. If the current results showed significant match advantages, we had to evaluate the contribution of participants’ strategy. On the weak positive association of match advantages and mental rotation scores, we could argue that the available strategy to facilitate mental rotation contriubte less to the match advantage. However, it is hardly to indicate that the mental imagery generated from the probe sentences differed from the cognitive processing for mental rotation.

Although the current results were incompatible with past studies [i.e. @chenDoesObjectSize2020], the variations among laboratories and languages showed the laboratory practices would decide the results of match (dis)advantages. Beisdes the Internet studies, one of the critical laboratory practices was that participants required explicit hints to comprehend the probe sentences sufficiently. The variation of languages showed the requirements that researchers might design the language-specific hints to trigger the participants’ comprehensions.For example, the explict feedbacks of the latest accuracy will promote participants’ attention for the coming stimuli.


## Analysis Issues  

Although the sensitivity analysis indicated the required number of participants varied among languages, the sources of measurement errors are requiring explorations. One is the limited trials to estimate the orientation effects. From the past to the current studies, the orientation effects were summarized from 24 items (12 match and 12 mismatch). The variation among items could be too large to underestimate the condition means. For example, the orientation effect was 10 ms but the cross-trial variation was 200 ms. In a classical cognitive capacity measurement, such as Stroop task and flanker task, the suggested trial numbers are beyond one-hundred to decrease the trial-level noise [@rouderWhyMostStudies2019]. In addition to the measurement errors issue, our sensitivity analysis indicated that the massive collaborative study difficulty detected the true effect size in a design of a small number of trials. 

This study reflected the difficulty of investigating cognition across languages, especially when dealing with effects that require large sample sizes [see @lokenMeasurementErrorReplication2017; @vadilloUnderpoweredSamplesFalse2016]. In addition to substantial variation in the number of participants available for the investigated languages, the practices to distract the participants’ full comprehension of sentence meanings could bias the orientation effects.Twelve languages in this study had one participating team only or did not have sufficient data for the exploratory analysis. On the other hand, the German results indicate that the collected data could reduce the biased estimates among the laboratories. This mass-collaboration model has the benefit to detect the small effect and have a reliable estimation than single-team studies.

## Theoretical Issues

Mental simulation theories of comprehension have suggested that cognitive processing converts discourse into either abstract symbols or grounded mental representations [@barsalouPerceptualSymbolSystems1999; @barsalouSimulationSituatedConceptualization2009; @zwaan_embodiment_2014]. On the other hand, neither theoretical view constituted the priming-based mechanism for the reading task as like sentence-picture verifications. Eventually  researchers are unable to improve their understanding on the general language comprehension [@kaschakEmbodimentLabTheory2021]. Without theoretical guidelines we can not confirm that the orientation effect of German is the product of mental simulations. We also can not accept the null effect in many languages according to the assumption that some language-specific aspects failed to initiate or inhibit the mental simulations. As previously discussed, we learned the measurement errors were from the stimuli content and the secondary task. Without a clear theoretical guideline, researchers hardly specify which physical property robustly facilitate the verification responses and improve the method to precisely measure the mental simulation processing. 

The original probe sentences [see @stanfield_effect_2001; @zwaanRevisitingMentalSimulation2012]  were the researchers’ creations which were compatible with the experimental demands but did not capture the theoretical complexity. These sentences described the interaction between one actor and one object. The other study [@chenDoesObjectSize2020] that found the orientation effect used the researchers’ created sentences as well. In comparison with the simple sentences (e.g., Chen et al. used I saw “something”), it addressed how the English participants from the original study comprehend the sentences and which language-specific aspects may alter the sentence content in the non-English studies. We suggest the further explorations could employ the original object pictures after simple and complex sentences. The results will help establish specific guidelines for exploring the sentence content.

A secondary task in the sentence-picture verification was used to encourage the participants to understand the probe sentences. In the verification task the participants could make responses without realizing the sentence content. A secondary task asked the probe contents or meanings would require participants to process the sentences. There has been the worry if the secondary task inspired the use of strategies instead of comprehension [e.g., @rommersObjectShapeOrientation2013]. This set of studies require the explorations of secondary task demands (memory checks; comprehension questions) and arrangements (fixed trials; flexible trials). These studies are necessary to distinguish the effects from the targeted cognitive processing and strategy in many language topics, such as semantic priming [@mcnamaraSemanticPrimingPerspectives2005].