---
title: 'Appendix 5: Planned analysis for imagery scores'
#tags: `PSA002`
output: html_document
#header-includes:
#  - \usepackage{caption}
#  - \usepackage{float}
#  - \captionsetup[table]{name=Table S,labelsep = period}
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lme4)
library(lmerTest)
library(ggplot2)
library(sjPlot)

# Import multiple-bytes string in English system
Sys.setlocale("LC_ALL","English") 
```



```{r load_info, message=FALSE, warning=FALSE, include=FALSE}
# Load lab information
lab_info <- ##dirname(getwd()) %>%
  dir(path = "..",full.names = TRUE, recursive = TRUE, include.dirs = TRUE, pattern = "Lab_info.csv")  %>%
  read_csv()

lab_fin <- ##dirname(getwd()) %>%
  dir(path = "..",full.names = TRUE, recursive = TRUE, include.dirs = TRUE, pattern = "lab_fin.csv")  %>%
  read_csv()

# Load meta data of in site data: age, female numbers

insite_meta <- dir(path = "..",full.names = TRUE, recursive = TRUE, include.dirs = TRUE, pattern = "insite_meta.csv") %>%
  read_csv() 

# Load and summary meta data of online data: age, female numbers, language proficiency
osweb_meta <- dir(path = "..",full.names = TRUE, recursive = TRUE, include.dirs = TRUE, pattern = "jatos_meta.csv") %>%
  read_csv() %>%
  mutate(gender = ifelse(gender==1,"FEMALE",ifelse(gender==2,"MALE","OTHER"))) %>%
  mutate(birth_year = as.numeric(birth_year)) %>%
  mutate(year = ifelse(birth_year > 21 & !is.na(birth_year), 1900 + birth_year, 2000 + birth_year)) %>%
  mutate(age = ifelse(!is.na(year),2021-year,NA)) %>%
  group_by(Batch) %>%
  summarise(N = n(), Female_N = sum(gender=="FEMALE",na.rm = TRUE), Age = round(mean(age, na.rm=TRUE),0), Proficiency = round(mean(lang_prof),0) )

SP_V <-  dir(path = "..",
      pattern = "all_rawdata_SP_V",   ## include in-site and internet data
      recursive = TRUE, full.names = TRUE) %>% 
      read_csv() %>%
      subset(correct == 1 & Match != "F") %>%  ## Exclude the incorrect responses and filler trials
      inner_join(select(lab_info, PSA_ID, Language), by = "PSA_ID") %>%
    distinct() %>% ## Merge the language aspects
    mutate(Source = if_else(opensesame_codename == "osweb","osweb","site"), 
           Subject = paste0(Source,"_",PSA_ID,"_",subject_nr)) ## Compose the unique participant id

```



```{r outlier-check, message=FALSE, warning=FALSE, include=FALSE, paged.print=TRUE}
get_intercept <- function(set) {
  #Subject = as.factor(subset(SP_V_tidy,PSA_ID == LAB_ID)$Subject) %>% levels() %>% as.numeric()
  
# Source = as.factor(subset(SP_V_tidy,PSA_ID == LAB_ID)$Source) %>% levels() %>% as.numeric()

 #Subject = paste(Source,"_",subject_nr)
 
  t <- cbind(#Source,
             #subject_nr,
             Subject = levels(as.factor(set$Subject)),
             (lmer(response_time ~ Match + (1|Subject), data = set) %>%
  coef())$Subject %>%
      as.tibble()%>%
  mutate(Outlier = `(Intercept)` > quantile(`(Intercept)`,probs=.75))
    )
  
  return(t)
}

LABS <- unique(SP_V$PSA_ID)

outliers_table <- NULL
for(lab_id in LABS){
  outliers_table<- get_intercept( subset(SP_V,PSA_ID == lab_id)) %>%
    mutate(LAB = lab_id) %>%
    rbind(outliers_table)
}
```

```{r PP_data_preparation, message=FALSE, warning=FALSE}

# Load PP verification responses
PP <- dir(path = "..",
      pattern = "all_rawdata_PP", 
      recursive = TRUE, full.names = TRUE) %>% 
      read_csv() %>%
      subset(correct == 1 & Identical != "F")  %>%  ## Exclude the incorrect responses and filler trials
      inner_join(select(lab_info, PSA_ID, Language), by = "PSA_ID") %>%
    distinct() %>% ## Merge the language aspects
    mutate(Source = if_else(opensesame_codename == "osweb","osweb","site"), 
           Subject = paste0(Source,"_",PSA_ID,"_",subject_nr)) ## Compose the unique participant id

## Tidy PP data for mixed linear model
PP_site_tidy <- PP %>% 
    filter(Source!="osweb") 

## Tidy PP data for mixed linear model
PP_osweb_tidy <-  PP %>%
      filter(Source=="osweb") %>%   # include jatos data
      subset(correct == 1 & Identical != "F")  %>%  ## Exclude the incorrect responses and filler trials
    distinct() %>% ## Merge the language aspects
    filter(!(PSA_ID == "USA_033" & subject_nr == 39)) ## exclude this participant who had not complete PP

PP_tidy = bind_rows(PP_site_tidy, PP_osweb_tidy)

## Dataset for mixed-effect model
PP_lme_data <- PP_tidy %>% left_join(outliers_table, by=c("PSA_ID" = "LAB", "Subject" = "Subject")) %>%  ## filter the outliers by SP_V data
  filter(Outlier == FALSE) 

PP_lme_data$Language <- ifelse(PP_lme_data$Language == "Magyar","Hungarian",PP_lme_data$Language)
PP_lme_data$Language <- ifelse(PP_lme_data$Language ==  "Simple Chinese", "Simplified Chinese",PP_lme_data$Language)

PP_lme_data <- mutate(PP_lme_data,
                        Identical= factor(Identical,
                          levels = c("Y","N"),
                          labels = c("SAME","DIFF")))
```

### Planned analysis: Interaction of imagery scores and langauges

We evaluated the interaction of imagery scores and languages in three models. Based on the recommended practices(Barr et al., 2013; Brauer & Curtin, 2018), the models used the optimizer `bobyqa`. The final report decided `PP.lang.zero_slope.cor.lme` the best fitted model.


```{r PP_lang_lme, message=FALSE, warning=FALSE}
## standardized the imagery score
PP_lme_data$Language <- if_else(PP_lme_data$Language=="English","0English",PP_lme_data$Language)

PP.lang.zero_slope.cor.lme <- lmerTest::lmer(response_time ~ 
                    Identical*Language +                # Fixed effect
                    (1 | Subject) +   # By-subject random intercept
                    (1 | Picture1) +   # By-item random intercept
                    (1 | PSA_ID),    # By-lab random intercept
#                    (z_Identical || PSA_ID),    # By-lab random slopes
                    data = PP_lme_data,
                    #method = 'KR',               # Calculate p values using Kenward-Roger method 
                    control = lmerControl(optimizer = "bobyqa",optCtrl = list(maxfun = 1e6)) # Increase maximum number of iterations to facilitate model convergence 
                    ) 


PP.lang.slopes.nocor.lme <- lmerTest::lmer(response_time ~ 
                    Identical*Language +                # Fixed effect
                    (1 | Subject) +   # By-subject random intercept
                    (1 | Picture1) +   # By-item random intercept
                    (Identical || PSA_ID),    # By-lab random intercept
                    data = PP_lme_data,
                    #method = 'KR',               # Calculate p values using Kenward-Roger method 
                    control = lmerControl(optimizer = "bobyqa",optCtrl = list(maxfun = 1e6)) # Increase maximum number of iterations to facilitate model convergence 
                    ) 

PP.lang.slopes.cor.lme <- lmerTest::lmer(response_time ~ 
                    Identical*Language +                # Fixed effect
                    (1 | Subject) +   # By-subject random intercept
                    (1 | Picture1) +   # By-item random intercept
                    (Identical | PSA_ID),    # By-lab random intercept
                    data = PP_lme_data,
                    #method = 'KR',               # Calculate p values using Kenward-Roger method 
                    control = lmerControl(optimizer = "bobyqa",optCtrl = list(maxfun = 1e6)) # Increase maximum number of iterations to facilitate model convergence 
                    ) 

tab_model(PP.lang.zero_slope.cor.lme)
tab_model(PP.lang.slopes.nocor.lme)
tab_model(PP.lang.slopes.cor.lme)
```