---
title: 'Appendix 2: Public records of intra-lab analysis'
#tags: `PSA002`
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Raw data and Logs

The link to access the public site: https://scgeeker.github.io/PSA002_log_site/index.html

If you want to check the sequential analysis result of a team, at first you have to identify the ID and language of this team from "Overview" page. Next you will navigate to the language page under the banner "Tracking Logs". For example, you want to see the result of "GBR_005". Navigate "Tracking Logs -> English". Search the figure by ID "GBR_005".

The source files of the public site are available in the github repository:
https://github.com/SCgeeker/PSA002_log_site

All the raw data and log files are compressed in the project OSF repository. Direct access link: https://osf.io/rg8a3/

The R code to conduct the Bayesian sequential analysis is available at "data_seq_analysis.R". Direct access link: https://github.com/SCgeeker/PSA002_log_site/blob/master/data_seq_analysis.R


**Note 1** AUS_002 was unavailable because of the incorrect practices. Their raw data are accessible at the OSF ( https://osf.io/j3qba ). USA_067, BRA_004 and POL_004 were unavailable because the teams withdrew.


**Note 2** Some mistakes happened between the collaborators' communications and required advanced data wrangling. For example, some AUS_091 participants were assigned to NZL_005. The Rmd file in NZL_005 folder were used to identify the AUS_091 participants' data then move them to AUS_091 folder.


## Tidy data

All the planned analysis were conducted in terms of the filtered raw data. We split the raw data into three parts: Sentence-picture verification responses (https://osf.io/msd97/); Responses of memory trials (https://osf.io/4duce/); Picture-picture verification responses (https://osf.io/qfrhu/). 